[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "motor>=3.7.1",
    "pymongo>=4.14.0",
    "pyrogram>=2.0.106",
]
